package cz.topolik.xssfinder.v2.wood;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;

/**
 * @author Tomas Polesovsky
 */
public class Tree implements Comparable<Tree> {
    private File root;
    private File continent;
    private String name;
    private List<String> rings = Collections.emptyList();

    public static boolean isTree(File file) {
        return !file.isDirectory() && (file.getName().endsWith(".java") || file.getName().endsWith(".tld"));
    }

    public Tree(File root, File continent) {
        this.root = root;
        this.continent = continent;
        name = root.getAbsolutePath();
    }

    public void examineByAnt() {
        List<String> rings = new ArrayList<String>();
        try {
            Scanner ant = new Scanner(root);

            while (ant.hasNextLine()) {
                rings.add(bite(ant.nextLine()));
            }

            this.rings = Collections.unmodifiableList(rings);

        } catch (FileNotFoundException ex) {
            throw new AntException("Ant wasn't able to examine a tree :(", ex);
        }
    }

    protected String bite(String s) {
        return s.trim();
    }

    /**
     * Regonize if it's a JSPs compiled into Java class using Jasper
     *
     * @return true when the file is a compiled JSP file
     */
    public boolean isLinden() {
        if (rings.size() == 0) {
            throw new AntException("Please call ants to examine the tree first!");
        }
        return rings.size() > 1 && rings.get(1).startsWith(" * Generated by the Jasper component of Apache Tomcat");
    }

    /**
     * Regonize if it's a Java file, not JSP
     *
     * @return true when the file is a Java file and is not compiled JSP
     */
    public boolean isBirch() {
        return name.endsWith(".java") && !isLinden();
    }

    /**
     * Regonize if it's a Java Taglib definition (.tld) file
     *
     * @return true when the file is a tld file
     */
    public boolean isChestnut() {
        return name.endsWith(".tld");
    }


    public File getRoot() {
        return root;
    }

    public String getName() {
        return name;
    }

    public String getRing(int ringNum) {
        return rings.get(ringNum);
    }

    public List<String> getRings() {
        return rings;
    }

    public File getContinent() {
        return continent;
    }

    public String melt() {
        StringBuffer sb = new StringBuffer();
        for (String ring : rings) {
            sb.append(ring);
        }
        return sb.toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Tree)) return false;

        Tree tree = (Tree) o;

        if (!root.equals(tree.root)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return root.hashCode();
    }

    @Override
    public int compareTo(Tree o) {
        if (o == null) {
            return 1;
        }

        return o.root.compareTo(root);
    }
}
