package cz.topolik.xssfinder.v2.wood;

import cz.topolik.xssfinder.v2.animal.bug.BirchBug;
import cz.topolik.xssfinder.v2.animal.bug.ChestnutBug;
import cz.topolik.xssfinder.v2.animal.bug.LindenBurg;
import cz.topolik.xssfinder.v2.animal.bug.TreeBug;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Scanner;

/**
 * @author Tomas Polesovsky
 */
public class Tree implements Comparable<Tree> {
    private File root;
    private File continent;
    private String name;
    private List<String> rings = Collections.emptyList();
    private TreeBug treeBug;

    public Tree(File root, File continent) {
        this.root = root;
        this.continent = continent;
        name = root.getAbsolutePath();
    }

    public static boolean isTree(File file) {
        return !file.isDirectory() && (file.getName().endsWith(".java") || file.getName().endsWith(".tld"));
    }

    public void examineByAnt() {
        Scanner ant = null;
        try {
            ant = new Scanner(root);
        } catch (FileNotFoundException ex) {
            throw new AntException("Ant wasn't able to examine a tree :(", ex);
        }

        List<String> rings = new ArrayList<String>();
        while (ant.hasNextLine()) {
            rings.add(bite(ant.nextLine()));
        }

        this.rings = Collections.unmodifiableList(rings);

        this.treeBug = isLinden() ? new LindenBurg() : isBirch() ? new BirchBug() : new ChestnutBug();
    }

    public void prepareTree(){
        treeBug.prepare(this);
    }

    protected String bite(String s) {
        return s.trim();
    }

    /**
     * Regonize if it's a JSPs compiled into Java class using Jasper
     *
     * @return true when the file is a compiled JSP file
     */
    public boolean isLinden() {
        if (rings.size() == 0) {
            throw new AntException("Please call ants to examine the tree first!");
        }

        return rings.size() > 1 && rings.get(1).startsWith("* Generated by the Jasper component of Apache Tomcat");
    }

    /**
     * Regonize if it's a Java file, not JSP
     *
     * @return true when the file is a Java file and is not compiled JSP
     */
    public boolean isBirch() {
        return name.endsWith(".java") && !isLinden();
    }

    /**
     * Regonize if it's a Java Taglib definition (.tld) file
     *
     * @return true when the file is a tld file
     */
    public boolean isChestnut() {
        return name.endsWith(".tld");
    }


    public File getRoot() {
        return root;
    }

    public String getName() {
        return name;
    }

    public String getRing(int ringNum) {
        return rings.get(ringNum);
    }

    public List<String> getRings() {
        return rings;
    }

    public File getContinent() {
        return continent;
    }

    public String melt() {
        StringBuffer sb = new StringBuffer();
        for (String ring : rings) {
            sb.append(ring);
            sb.append('\n');
        }
        return sb.toString();
    }

    public TreeBug getTreeBug() {
        return treeBug;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Tree)) return false;

        Tree tree = (Tree) o;

        if (!root.equals(tree.root)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        return root.hashCode();
    }

    @Override
    public int compareTo(Tree o) {
        if (o == null) {
            return 1;
        }

        return o.root.compareTo(root);
    }

    @Override
    public String toString() {
        return "Tree{" +
                "name='" + name + '\'' +
                '}';
    }
}
